import * as z from 'zod';
import type { Prisma } from '@prisma/client';
import { SortOrderSchema } from '../enums/SortOrder.schema'

const makeSchema = () => z.object({
  id: SortOrderSchema.optional(),
  name: SortOrderSchema.optional(),
  email: SortOrderSchema.optional(),
  phone: SortOrderSchema.optional(),
  company: SortOrderSchema.optional(),
  message: SortOrderSchema.optional(),
  total: SortOrderSchema.optional(),
  status: SortOrderSchema.optional(),
  userId: SortOrderSchema.optional(),
  createdAt: SortOrderSchema.optional(),
  updatedAt: SortOrderSchema.optional(),
  cep: SortOrderSchema.optional(),
  cnpj: SortOrderSchema.optional(),
  cpf: SortOrderSchema.optional(),
  adminNotes: SortOrderSchema.optional(),
  approvedAt: SortOrderSchema.optional(),
  approvedBy: SortOrderSchema.optional(),
  convertedToRentalId: SortOrderSchema.optional(),
  deliveryAddress: SortOrderSchema.optional(),
  deliveryFee: SortOrderSchema.optional(),
  deliveryType: SortOrderSchema.optional(),
  deposit: SortOrderSchema.optional(),
  discount: SortOrderSchema.optional(),
  endDate: SortOrderSchema.optional(),
  finalTotal: SortOrderSchema.optional(),
  internalNotes: SortOrderSchema.optional(),
  pickupFee: SortOrderSchema.optional(),
  priority: SortOrderSchema.optional(),
  rejectedAt: SortOrderSchema.optional(),
  rejectedBy: SortOrderSchema.optional(),
  rejectionReason: SortOrderSchema.optional(),
  startDate: SortOrderSchema.optional(),
  subtotal: SortOrderSchema.optional(),
  taxes: SortOrderSchema.optional(),
  validUntil: SortOrderSchema.optional(),
  originalTotal: SortOrderSchema.optional(),
  priceAdjustmentReason: SortOrderSchema.optional(),
  priceAdjustedAt: SortOrderSchema.optional(),
  priceAdjustedBy: SortOrderSchema.optional(),
  lateFee: SortOrderSchema.optional(),
  lateFeeApproved: SortOrderSchema.optional(),
  lateFeeApprovedAt: SortOrderSchema.optional(),
  lateFeeApprovedBy: SortOrderSchema.optional(),
  damages: SortOrderSchema.optional(),
  misuse: SortOrderSchema.optional()
}).strict();
export const QuoteCountOrderByAggregateInputObjectSchema: z.ZodType<Prisma.QuoteCountOrderByAggregateInput> = makeSchema() as unknown as z.ZodType<Prisma.QuoteCountOrderByAggregateInput>;
export const QuoteCountOrderByAggregateInputObjectZodSchema = makeSchema();
