packages:
  - 'app'
  - 'components'
  - 'hooks'
  - 'lib'
  - 'middlewares'
  - 'prisma'
  - 'schemas'
  - 'types'
  - 'tests'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@vercel/speed-insights'
  - esbuild
  - prisma
  - sharp
