import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { DeliveryOrderByWithRelationInputObjectSchema as DeliveryOrderByWithRelationInputObjectSchema } from './objects/DeliveryOrderByWithRelationInput.schema';
import { DeliveryWhereInputObjectSchema as DeliveryWhereInputObjectSchema } from './objects/DeliveryWhereInput.schema';
import { DeliveryWhereUniqueInputObjectSchema as DeliveryWhereUniqueInputObjectSchema } from './objects/DeliveryWhereUniqueInput.schema';
import { DeliveryCountAggregateInputObjectSchema as DeliveryCountAggregateInputObjectSchema } from './objects/DeliveryCountAggregateInput.schema';
import { DeliveryMinAggregateInputObjectSchema as DeliveryMinAggregateInputObjectSchema } from './objects/DeliveryMinAggregateInput.schema';
import { DeliveryMaxAggregateInputObjectSchema as DeliveryMaxAggregateInputObjectSchema } from './objects/DeliveryMaxAggregateInput.schema';
import { DeliveryAvgAggregateInputObjectSchema as DeliveryAvgAggregateInputObjectSchema } from './objects/DeliveryAvgAggregateInput.schema';
import { DeliverySumAggregateInputObjectSchema as DeliverySumAggregateInputObjectSchema } from './objects/DeliverySumAggregateInput.schema';

export const DeliveryAggregateSchema: z.ZodType<Prisma.DeliveryAggregateArgs> = z.object({ orderBy: z.union([DeliveryOrderByWithRelationInputObjectSchema, DeliveryOrderByWithRelationInputObjectSchema.array()]).optional(), where: DeliveryWhereInputObjectSchema.optional(), cursor: DeliveryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DeliveryCountAggregateInputObjectSchema ]).optional(), _min: DeliveryMinAggregateInputObjectSchema.optional(), _max: DeliveryMaxAggregateInputObjectSchema.optional(), _avg: DeliveryAvgAggregateInputObjectSchema.optional(), _sum: DeliverySumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.DeliveryAggregateArgs>;

export const DeliveryAggregateZodSchema = z.object({ orderBy: z.union([DeliveryOrderByWithRelationInputObjectSchema, DeliveryOrderByWithRelationInputObjectSchema.array()]).optional(), where: DeliveryWhereInputObjectSchema.optional(), cursor: DeliveryWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), DeliveryCountAggregateInputObjectSchema ]).optional(), _min: DeliveryMinAggregateInputObjectSchema.optional(), _max: DeliveryMaxAggregateInputObjectSchema.optional(), _avg: DeliveryAvgAggregateInputObjectSchema.optional(), _sum: DeliverySumAggregateInputObjectSchema.optional() }).strict();