/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any */
import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { MaintenanceOrderByWithRelationInputObjectSchema as MaintenanceOrderByWithRelationInputObjectSchema } from './objects/MaintenanceOrderByWithRelationInput.schema';
import { MaintenanceWhereInputObjectSchema as MaintenanceWhereInputObjectSchema } from './objects/MaintenanceWhereInput.schema';
import { MaintenanceWhereUniqueInputObjectSchema as MaintenanceWhereUniqueInputObjectSchema } from './objects/MaintenanceWhereUniqueInput.schema';
import { MaintenanceCountAggregateInputObjectSchema as MaintenanceCountAggregateInputObjectSchema } from './objects/MaintenanceCountAggregateInput.schema';
import { MaintenanceMinAggregateInputObjectSchema as MaintenanceMinAggregateInputObjectSchema } from './objects/MaintenanceMinAggregateInput.schema';
import { MaintenanceMaxAggregateInputObjectSchema as MaintenanceMaxAggregateInputObjectSchema } from './objects/MaintenanceMaxAggregateInput.schema';
import { MaintenanceAvgAggregateInputObjectSchema as MaintenanceAvgAggregateInputObjectSchema } from './objects/MaintenanceAvgAggregateInput.schema';
import { MaintenanceSumAggregateInputObjectSchema as MaintenanceSumAggregateInputObjectSchema } from './objects/MaintenanceSumAggregateInput.schema';

export const MaintenanceAggregateSchema: z.ZodType<Prisma.MaintenanceAggregateArgs> = z.object({ orderBy: z.union([MaintenanceOrderByWithRelationInputObjectSchema, MaintenanceOrderByWithRelationInputObjectSchema.array()]).optional(), where: MaintenanceWhereInputObjectSchema.optional(), cursor: MaintenanceWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), MaintenanceCountAggregateInputObjectSchema ]).optional(), _min: MaintenanceMinAggregateInputObjectSchema.optional(), _max: MaintenanceMaxAggregateInputObjectSchema.optional(), _avg: MaintenanceAvgAggregateInputObjectSchema.optional(), _sum: MaintenanceSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.MaintenanceAggregateArgs>;

export const MaintenanceAggregateZodSchema = z.object({ orderBy: z.union([MaintenanceOrderByWithRelationInputObjectSchema, MaintenanceOrderByWithRelationInputObjectSchema.array()]).optional(), where: MaintenanceWhereInputObjectSchema.optional(), cursor: MaintenanceWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), MaintenanceCountAggregateInputObjectSchema ]).optional(), _min: MaintenanceMinAggregateInputObjectSchema.optional(), _max: MaintenanceMaxAggregateInputObjectSchema.optional(), _avg: MaintenanceAvgAggregateInputObjectSchema.optional(), _sum: MaintenanceSumAggregateInputObjectSchema.optional() }).strict();