import * as z from 'zod';
import { QuoteStatusSchema } from '../../enums/QuoteStatus.schema';
import { DeliveryTypeSchema } from '../../enums/DeliveryType.schema';
// prettier-ignore
export const QuoteInputSchema = z.object({
    id: z.string(),
    name: z.string(),
    email: z.string(),
    phone: z.string(),
    company: z.string().optional().nullable(),
    message: z.string().optional().nullable(),
    total: z.number(),
    status: QuoteStatusSchema,
    userId: z.string().optional().nullable(),
    createdAt: z.date(),
    updatedAt: z.date(),
    cep: z.string().optional().nullable(),
    cnpj: z.string().optional().nullable(),
    cpf: z.string().optional().nullable(),
    adminNotes: z.string().optional().nullable(),
    approvedAt: z.date().optional().nullable(),
    approvedBy: z.string().optional().nullable(),
    convertedToRentalId: z.string().optional().nullable(),
    deliveryAddress: z.unknown().optional().nullable(),
    deliveryFee: z.number().optional().nullable(),
    deliveryType: DeliveryTypeSchema.optional().nullable(),
    deposit: z.number().optional().nullable(),
    discount: z.number().optional().nullable(),
    endDate: z.date().optional().nullable(),
    finalTotal: z.number().optional().nullable(),
    internalNotes: z.string().optional().nullable(),
    pickupFee: z.number().optional().nullable(),
    priority: z.number().int().optional().nullable(),
    rejectedAt: z.date().optional().nullable(),
    rejectedBy: z.string().optional().nullable(),
    rejectionReason: z.string().optional().nullable(),
    startDate: z.date().optional().nullable(),
    subtotal: z.number().optional().nullable(),
    taxes: z.number().optional().nullable(),
    validUntil: z.date().optional().nullable(),
    originalTotal: z.number().optional().nullable(),
    priceAdjustmentReason: z.string().optional().nullable(),
    priceAdjustedAt: z.date().optional().nullable(),
    priceAdjustedBy: z.string().optional().nullable(),
    lateFee: z.number().optional().nullable(),
    lateFeeApproved: z.boolean().optional().nullable(),
    lateFeeApprovedAt: z.date().optional().nullable(),
    lateFeeApprovedBy: z.string().optional().nullable(),
    damages: z.unknown().optional().nullable(),
    misuse: z.unknown().optional().nullable(),
    payments: z.array(z.unknown()),
    items: z.array(z.unknown()),
    approvedByUser: z.unknown().optional().nullable(),
    rejectedByUser: z.unknown().optional().nullable(),
    user: z.unknown().optional().nullable(),
    rentals: z.array(z.unknown())
}).strict();

export type QuoteInputType = z.infer<typeof QuoteInputSchema>;
