/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any */
import * as z from 'zod';

export const NotificationTypeSchema = z.enum(['QUOTE_CREATED', 'QUOTE_APPROVED', 'QUOTE_REJECTED', 'QUOTE_EXPIRED', 'RENTAL_CREATED', 'RENTAL_ACTIVE', 'RENTAL_COMPLETED', 'RENTAL_OVERDUE', 'RENTAL_RETURN_REMINDER', 'PAYMENT_PENDING', 'PAYMENT_RECEIVED', 'PAYMENT_OVERDUE', 'PAYMENT_FAILED', 'DELIVERY_SCHEDULED', 'DELIVERY_IN_TRANSIT', 'DELIVERY_COMPLETED', 'DELIVERY_FAILED', 'PICKUP_SCHEDULED', 'PICKUP_COMPLETED', 'EQUIPMENT_AVAILABLE', 'CONTRACT_SENT', 'CONTRACT_SIGNED', 'CONTRACT_EXPIRED', 'SYSTEM_MAINTENANCE', 'SYSTEM_UPDATE', 'PROMOTION'])

export type NotificationType = z.infer<typeof NotificationTypeSchema>;