// components/dialogs/icon-customization-data.ts
import type { AllIconNames } from '@/lib/constants/all-icons'
import { CUSTOM_ICONS } from '@/components/icons/custom'

export type IconPickerTab = 'emoji' | 'icons' | 'custom'

export interface EmojiGroup {
  id: string
  label: string
  glyph?: string
  emojis: string[]
}

export interface IconGroup {
  id: string
  label: string
  glyph?: string
  icons: AllIconNames[]
}

export const ICON_PICKER_TABS: Array<{ value: IconPickerTab; label: string }> = [
  { value: 'emoji', label: 'Emoji' },
  { value: 'icons', label: 'Ícones' },
  { value: 'custom', label: 'Personalizado' },
]

export const ICON_LIBRARY_FILTERS: Array<{
  value: 'lucide' | 'custom'
  label: string
}> = [
  { value: 'lucide', label: 'Lucide' },
  { value: 'custom', label: 'Personalizados' },
]

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    id: 'recent',
    label: 'Recentes',
    glyph: '🕒',
    emojis: ['😀', '😃', '😄', '😁', '😆', '😅', '🤣', '😂', '🙂', '🙃', '😉', '😊'],
  },
  {
    id: 'people',
    label: 'Pessoas',
    glyph: '😀',
    emojis: [
      '😀',
      '😃',
      '😄',
      '😁',
      '😆',
      '😅',
      '🤣',
      '😂',
      '🙂',
      '🙃',
      '😇',
      '🥰',
      '😍',
      '🤩',
      '😘',
      '😗',
      '😚',
      '😙',
      '😋',
      '😛',
      '😜',
      '🤪',
      '🤨',
      '🧐',
      '🤓',
      '😎',
      '🥸',
      '🤠',
      '🥳',
      '🥺',
      '😭',
      '😢',
      '😡',
      '🤬',
      '🤯',
      '🤗',
      '🤝',
    ],
  },
  {
    id: 'nature',
    label: 'Natureza',
    glyph: '🌿',
    emojis: [
      '🌱',
      '🌿',
      '☘️',
      '🍀',
      '🎋',
      '🍃',
      '🍂',
      '🍁',
      '🌷',
      '🌹',
      '🌺',
      '🌸',
      '🌼',
      '🌻',
      '🌞',
      '🌝',
      '🌛',
      '🌜',
      '⭐',
      '⚡',
      '🌈',
      '☔',
      '🌧️',
      '❄️',
      '🔥',
      '🌊',
    ],
  },
  {
    id: 'objects',
    label: 'Objetos',
    glyph: '🧰',
    emojis: [
      '🛠️',
      '🧰',
      '🔧',
      '🔨',
      '⚙️',
      '🪛',
      '🪚',
      '🧱',
      '🏗️',
      '⚒️',
      '🪜',
      '📦',
      '📁',
      '📄',
      '💡',
      '🔌',
      '🧲',
      '📡',
      '🖥️',
      '📱',
      '🕹️',
      '📷',
      '🎥',
      '🎧',
      '🎯',
      '🪙',
      '💳',
      '💼',
    ],
  },
  {
    id: 'symbols',
    label: 'Símbolos',
    glyph: '🔣',
    emojis: [
      '❤️',
      '💛',
      '💚',
      '💙',
      '💜',
      '🖤',
      '🤍',
      '💯',
      '✅',
      '❌',
      '⚠️',
      '🚫',
      '⚡',
      '✔️',
      '➕',
      '➖',
      '➗',
      '✖️',
      '🔺',
      '🔻',
      '🔸',
      '🔹',
      '🔷',
      '🔶',
      '🟥',
      '🟩',
      '🟦',
    ],
  },
  {
    id: 'flags',
    label: 'Bandeiras',
    glyph: '🚩',
    emojis: [
      '🇧🇷',
      '🇵🇹',
      '🇺🇸',
      '🇨🇦',
      '🇪🇸',
      '🇫🇷',
      '🇮🇹',
      '🇩🇪',
      '🇯🇵',
      '🇨🇳',
      '🇬🇧',
      '🇦🇷',
      '🇲🇽',
      '🇦🇺',
      '🇨🇱',
      '🇵🇪',
      '🇨🇴',
      '🇺🇾',
      '🇵🇾',
      '🇧🇴',
      '🇻🇪',
      '🇵🇰',
      '🇮🇳',
      '🏳️',
      '🏴',
    ],
  },
]

export const LUCIDE_ICON_GROUPS: IconGroup[] = [
  {
    id: 'construction',
    label: 'Construção & Ferramentas',
    glyph: '🛠️',
    icons: [
      'Package',
      'Wrench',
      'Hammer',
      'Building',
      'Building2',
      'Warehouse',
      'Factory',
      'Home',
      'Ruler',
      'Gauge',
      'Thermometer',
      'Shield',
    ] as AllIconNames[],
  },
  {
    id: 'transport',
    label: 'Transporte & Logística',
    glyph: '🚚',
    icons: [
      'Truck',
      'Car',
      'Bus',
      'Plane',
      'Ship',
      'Train',
      'Navigation',
      'Compass',
      'Globe',
      'MapPin',
      'Route',
    ] as AllIconNames[],
  },
  {
    id: 'people-status',
    label: 'Pessoas & Status',
    glyph: '👥',
    icons: [
      'Users',
      'User',
      'UserCog',
      'Contact',
      'IdCard',
      'Store',
      'Star',
      'Heart',
      'ThumbsUp',
      'Award',
      'Trophy',
      'Medal',
    ] as AllIconNames[],
  },
  {
    id: 'communication',
    label: 'Comunicação & Mídia',
    glyph: '💬',
    icons: [
      'Phone',
      'Mail',
      'Send',
      'MessageCircle',
      'MessageSquare',
      'Inbox',
      'Image',
      'Camera',
      'Video',
      'Music',
      'Speaker',
      'Play',
    ] as AllIconNames[],
  },
  {
    id: 'analytics',
    label: 'Indicadores & Métricas',
    glyph: '📊',
    icons: [
      'TrendingUp',
      'TrendingDown',
      'Activity',
      'BarChart',
      'PieChart',
      'LineChart',
      'Target',
      'Hash',
      'Calculator',
      'Sigma',
      'Percent',
      'Infinity',
    ] as AllIconNames[],
  },
  {
    id: 'weather',
    label: 'Clima & Ambiente',
    glyph: '⛅',
    icons: [
      'Sun',
      'Moon',
      'Cloud',
      'CloudRain',
      'CloudSnow',
      'Umbrella',
      'Wind',
      'CloudLightning',
      'Tornado',
      'Rainbow',
      'Sparkles',
      'Flame',
    ] as AllIconNames[],
  },
]

export const CUSTOM_ICON_GROUPS: IconGroup[] = [
  {
    id: 'custom-library',
    label: 'Ícones Personalizados',
    glyph: '✨',
    icons: Object.keys(CUSTOM_ICONS) as AllIconNames[],
  },
]
