name: CI/CD Pipeline (Simplified) - DISABLED

# DISABLED: Use ci.yml instead
on:
  workflow_dispatch: # Manual trigger only - workflow is disabled
  # push:
  #   branches: [main, develop]
  # pull_request:
  #   branches: [main, develop]

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: false # Disabled

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Verify pnpm installation
        run: |
          echo "PNPM version:"
          pnpm --version
          echo "PNPM location:"
          which pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm db:generate

      - name: Check Prisma setup
        run: pnpm check:prisma

      - name: Build application (skip type check)
        run: pnpm build

      - name: Build Storybook
        run: pnpm build-storybook

  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest
    if: false # Disabled

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm db:generate

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ./
